### ISSUE TITLE
deb and rpm packages.

### ISSUE THREAD

**Issue by chris001** [trusteddomainproject/OpenARC#29]
@mskucherawy Kudos on this project - OpenARC!
Would it be possible for you to setup a small virtual build server to automatically build `deb` and `rpm` packages for the most common linux distros, debian, ubuntu, centos, fedora, etc.?

**Comment by icb-** [comment]
There are already build systems for a lot of these, if you upload source packages. [COPR](https://copr.fedorainfracloud.org/) covers Fedora and CentOS. [PPA](https://help.launchpad.net/Packaging/PPA) covers Ubuntu, and maybe Debian.

That said, I think the real blocker here is having a tagged release.

**Comment by mdomsch** [comment]
I'd be happy to package it for Fedora and EPEL, once there's a stable release.  I expect to meet stable release criteria there would have to be unit tests and a corpus of example messages (both well-formed and not) to prove functionally correct.  Most of the items currently in the issues list would need to be addressed.

FWIW, the spec file in contrib/spec/openarc.spec is a fine start.   I found it needing
 `autoreconf --install
`
just before calling ./configure.  (yes, that's not best practice to put in the spec I know, but it suffices in place of an actual release tarball that includes configure and friends).

Then one can easily generate the source tarball with 
`
git archive --format tar --prefix=openarc-0.1.0/ HEAD | gzip -9 > rpmbuild/SOURCES/openarc-0.1.0.tar.gz
`
drop the spec file into rpmbuild/SPECS/
and in the rpmbuild directory do:
`rpmbuild -ba --define "_topdir $(pwd)" SPECS/openarc.spec
`
and get the resulting packages out of rpmbuild/RPMS/.

**Comment by icb-** [comment]
`contrib/spec/openarc.spec` still needs some work before it should be used for "real" packages. 

Most notably, it should use a systemd unit instead of a SysV init script for RHEL/CentOS >= 7. This is important to get right from the start, since RHEL best practices strongly recommend against moving from SysV to systemd in a package upgrade. (Mostly because you lose whether the administrator has the service set to start on boot, and revert to the package's default.)

The spec is also missing a bunch of build requirements, like `libbsd-devel`, and `libtool`

`opendkim` got this mostly right [in its spec](http://pkgs.fedoraproject.org/cgit/rpms/opendkim.git/tree/opendkim.spec?h=epel7).

Unfortunately, I don't expect to have the time to submit a PR to clean this up for a while.

**Comment by mdomsch** [comment]
https://github.com/mskucherawy/OpenARC/pull/51
